# Data Science in Psychology and Neuroscience

## Class info:
* Week #5
* Day: February 17, 2026
* Time: 9:30—10:45 AM
* Location: Logan Hall 125
* <a href="https://forms.microsoft.com/r/26vAcJWrwH">Click here to submit your attendance for Week 5, Question 9!</a>
  
## Instructor info:
* Dr. Jeremy Hogeveen
* jhogeveen@unm.edu
* Logan Hall 281 (Office Hours By Appointment)
  
## Syllabus:
* <a href="https://www.dropbox.com/scl/fi/6fs6fi4kvkwtxn7j7x8ua/PSY450650_DSPN_Spring2026_Syllabus.pdf?rlkey=148e5t4ah8q2n1daclt7mp0h6&dl=0">Download here</a>

## Today's topics:
1. Data Wrangling intro.
2. Introducing Numpy
    1. The ndarray
3. Introducing Pandas (stealing heavily from this <a href="https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf">Cheatsheet</a>)
    1. Creating a data frame
    2. Reading an existing data frame
    3. Reshaping
    4. Subsetting
    5. Adding columns
    6. Combining data frames

# Section 1: Data Wrangling & Pandas Intro

## 1.1 _What is_ wrangling?

<img src="img/data_wrangling_schematic.png" width="600">

<img src="img/lotr.gif">

## 1.2 _What is_ Numpy?

* The backbone package of all numeric and scientific computing in Python
    * Pandas and many other packages _depend_ on Numpy

<img src="img/numpy.png" width=300>

## 1.3 _What is_ Pandas?

* A data wrangling _package_ for Python
    * Takes a lot of what is good about R and brings it into a Python general-purpose programming env

<img src="img/pandas.jpeg" width=300>

# Section 2: Introducing _Numpy_

## 2.1 the _ndarray_
* The core data structure in Numpy is the n-dimensional array (or _ndarray_)
    * Function similarly to MATLAB arrays
    * An array with an arbitrary number of dimensions
    * Unlike _lists_, every element has to have the same data type

In [4]:
# importing and name numpy package
import numpy as np

# storing a list of numbers
list_of_numbers = [1, 2, 3, 5, 6]
print(list_of_numbers)
# list_of_numbers.shape

# converting to a numpy array
array = np.array(list_of_numbers)
print(array)
array.shape

[1, 2, 3, 5, 6]
[1 2 3 5 6]


(5,)

In [5]:
# arrays can have multiple dimensions
list_of_numbers_1 = [4,3,9,1,6]
array_1 = np.array([list_of_numbers,list_of_numbers_1])
print(array_1)

[[1 2 3 5 6]
 [4 3 9 1 6]]


In [8]:
print("The shape of the first array is:",array.shape)
print("The shape of the second array is:",array_1.shape)

The shape of the first array is: (5,)
The shape of the second array is: (2, 5)


In [18]:
# print("The dtype of the array is:",array.dtype)
print("The item size of the array is:",array.itemsize)
print("the strides of the first array is:",array.strides)
print("the strides of the second array is:",array_1.strides)

array_3 = np.array(['one','two','three','four','five'])
print(array_3)
array_3.itemsize

array_4 = np.array([1.11,2.22,3.33,4.44,5.55])
print(array_4)
array_4.itemsize

array_4[3]

The item size of the array is: 8
the strides of the first array is: (8,)
the strides of the second array is: (40, 8)
['one' 'two' 'three' 'four' 'five']
[1.11 2.22 3.33 4.44 5.55]


np.float64(4.44)

# Section 3: Introducing _Pandas_

* Pandas allows us to work with _Tidy data_
    * General organizational structure used to hold and manipulate data objects used in R and Pandas
    
<img src="img/tidy_data.png" width="650">

* This enables you to perform __vectorized operations__ on your data
    * Pandas (and tidyverse/dplyr in R) preserve your observations while you run those operations
    
<img src="img/tidy_data_vectorized_operations.png" width="450">

## 3.1 Creating a data frame
* Can create a tidy data frame in Pandas using similar formatting to a _dictinary_ object.

In [20]:
import pandas as pd

# create a pandas data frane
my_df = pd.DataFrame({'A': ['A0','A1','A2','A3']})
print(my_df)

    A
0  A0
1  A1
2  A2
3  A3


In [21]:
# can also add lists directly to the df
list_a = ['A0','A1','A2','A3']
list_b = ['B0','B1','B2','B3']
list_c = ['C0','C1','C2','C3']

my_df_2 = pd.DataFrame({'A': list_a,
                       'B': list_b,
                       'C': list_c})

print(my_df_2)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3


In [22]:
# We can also create the data frame by assignign ...
# row values, ...
list_row1 = ['A0','B0','C0']
list_row2 = ['A1','B1','C1']
list_row3 = ['A2','B2','C2']
list_row4 = ['A3','B3','C3']
row_values = [list_row1, list_row2, list_row3, list_row4]
print(row_values)
# indices, ...
custom_indices = ['t1','t2','t3','t4']
print(custom_indices)
#  and columns separately.
col_headers = ['v1','v2','v3']
print(col_headers)

my_df_3 = pd.DataFrame(row_values,index=custom_indices,columns=col_headers)
print(my_df_3)

[['A0', 'B0', 'C0'], ['A1', 'B1', 'C1'], ['A2', 'B2', 'C2'], ['A3', 'B3', 'C3']]
['t1', 't2', 't3', 't4']
['v1', 'v2', 'v3']
    v1  v2  v3
t1  A0  B0  C0
t2  A1  B1  C1
t3  A2  B2  C2
t4  A3  B3  C3


## 3.2 Reading an existing data frame

* More often, we have data we need to read in to wrangle.
    * Data can come from a local connected drive, a networked drive, or a remote server accessed over the web.
* Pandas specializes in reading in any data frame as long as it is _tab separated_ (aka "tabulated" or "tab-delimited")
    * comma separated values (csv)
    * tab separated values (tsv)
    * tab delimited text (txt)
    * Excel (.xlsx) can work, but requires an additional excel reader...
        * _conda install openpyxl_

In [35]:
# reading csv from a web source
df_subinfo = pd.read_csv("https://yeatmanlab.github.io/AFQBrowser-demo/data/subjects.csv")
print(df_subinfo.head())
# print(df_subinfo.tail())
# print(df_subinfo.shape)
# print(df_subinfo.shape[0])
# print(df_subinfo.shape[1])

   Unnamed: 0    subjectID  Age  Gender Handedness     IQ  IQ_Matrix  IQ_Vocab
0           0  subject_000   20    Male        NaN  139.0       65.0      77.0
1           1  subject_001   31    Male        NaN  129.0       58.0      74.0
2           2  subject_002   18  Female        NaN  130.0       63.0      70.0
3           3  subject_003   28    Male      Right    NaN        NaN       NaN
4           4  subject_004   29    Male        NaN    NaN        NaN       NaN


In [41]:
df_subinfo = pd.read_csv("https://yeatmanlab.github.io/AFQBrowser-demo/data/subjects.csv",
                         usecols=range(1,8))
print(df_subinfo.head())
df_subinfo.shape

     subjectID  Age  Gender Handedness     IQ  IQ_Matrix  IQ_Vocab
0  subject_000   20    Male        NaN  139.0       65.0      77.0
1  subject_001   31    Male        NaN  129.0       58.0      74.0
2  subject_002   18  Female        NaN  130.0       63.0      70.0
3  subject_003   28    Male      Right    NaN        NaN       NaN
4  subject_004   29    Male        NaN    NaN        NaN       NaN


(77, 7)

## 3.3 Reshaping data

### Melt (i.e. go from wide to long)

<img src="img/melt.png" width="400">

In [43]:
# example:L pulling IQ subscales and makling long
df_subinfo_long = pd.melt(df_subinfo,
                          id_vars=['subjectID','Age','Gender','Handedness','IQ'],
                         value_name = 'IQ_score',
                         var_name = 'IQ_scale')
print(df_subinfo_long)

       subjectID  Age  Gender Handedness     IQ   IQ_scale  IQ_score
0    subject_000   20    Male        NaN  139.0  IQ_Matrix      65.0
1    subject_001   31    Male        NaN  129.0  IQ_Matrix      58.0
2    subject_002   18  Female        NaN  130.0  IQ_Matrix      63.0
3    subject_003   28    Male      Right    NaN  IQ_Matrix       NaN
4    subject_004   29    Male        NaN    NaN  IQ_Matrix       NaN
..           ...  ...     ...        ...    ...        ...       ...
149  subject_072   40    Male      Right  134.0   IQ_Vocab      69.0
150  subject_073   50     NaN        NaN    NaN   IQ_Vocab       NaN
151  subject_074   40    Male      Right  122.0   IQ_Vocab      63.0
152  subject_075   17  Female      Right  118.0   IQ_Vocab      65.0
153  subject_076   17    Male      Right  121.0   IQ_Vocab      65.0

[154 rows x 7 columns]


### Pivot (i.e. go from long to wide)

<img src="img/pivot.png" width="600">

In [49]:
# example: moving IQ subcale scores back to wide format
df_subinfo_wide = df_subinfo_long.pivot(index = ['subjectID','Age','Gender','Handedness','IQ'],
                                       columns = 'IQ_scale',
                                       values='IQ_score')
# print(df_subinfo)
print(df_subinfo_wide)
print(df_subinfo_wide.reset_index().rename_axis(None,axis=1))

IQ_scale                                 IQ_Matrix  IQ_Vocab
subjectID   Age Gender Handedness IQ                        
subject_000 20  Male   NaN        139.0       65.0      77.0
subject_001 31  Male   NaN        129.0       58.0      74.0
subject_002 18  Female NaN        130.0       63.0      70.0
subject_003 28  Male   Right      NaN          NaN       NaN
subject_004 29  Male   NaN        NaN          NaN       NaN
...                                            ...       ...
subject_072 40  Male   Right      134.0       68.0      69.0
subject_073 50  NaN    NaN        NaN          NaN       NaN
subject_074 40  Male   Right      122.0       62.0      63.0
subject_075 17  Female Right      118.0       55.0      65.0
subject_076 17  Male   Right      121.0       59.0      65.0

[77 rows x 2 columns]
      subjectID  Age  Gender Handedness     IQ  IQ_Matrix  IQ_Vocab
0   subject_000   20    Male        NaN  139.0       65.0      77.0
1   subject_001   31    Male        NaN  129.0  